options:
    ganglia_metrics:
        type: boolean
        default: false
        description: |
          Enable metrics using Ganglia.  Note that enabling this option will
          have no effect if the service is not related to a ganglia service
          via the ganglia:master relation.  Enabling this option with the
          relation will issue a restart to the ResourceManager and all
          NodeManager components on all related slaves.
          See the README for more information.

